- name: openrouter/deepseek/deepseek-chat-v3-0324
  edit_format: diff
  use_repo_map: true
  reminder: sys
  examples_as_sys_msg: true
  caches_by_default: true
  extra_params:
    max_tokens: 8192
    extra_body:
      provider:
        order: ["Lambda"]
        allow_fallbacks: false

- name: openrouter/deepseek/deepseek-chat-v3-0324:free
  edit_format: diff
  weak_model_name: openrouter/deepseek/deepseek-chat-v3-0324:free
  use_repo_map: true
  examples_as_sys_msg: true
  caches_by_default: true
  use_temperature: false
  editor_model_name: openrouter/deepseek/deepseek-r1:free
  editor_edit_format: editor-diff

- name: gemini/gemini-2.5-pro-exp-03-25
  edit_format: diff-fenced
  use_repo_map: true
  weak_model_name: gemini/gemini-2.5-flash-preview-04-17

- name: openrouter/google/gemini-2.5-pro-exp-03-25:free
  edit_format: diff-fenced
  use_repo_map: true
  weak_model_name: openrouter/google/gemini-2.0-flash-exp:free

- name: openrouter/qwen/qwen3-235b-a22b:free
  edit_format: diff
  use_repo_map: true
