format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$rust\
$java\
$kotlin\
$gradle\
$time\
\n$character"""

[time]
disabled = true
time_format = '%T'
utc_time_offset = '+8'
style = "bg:#1d2230"
format = '[[$time](fg:#a0a9cb)]($style)'

[java]
format = '\[[$symbol($version)]($style)\]'

[gradle]
format = '\[[$symbol($version)]($style)\]'

